// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"time"
)

type Game struct {
	ID         int64
	WhiteUid   int64
	BlackUid   int64
	Result     string
	Moves      string
	FinishedAt time.Time
}

type User struct {
	Uid          int64
	Username     string
	PasswordHash string
	CreatedAt    time.Time
}
