definitions:
  server.ApiKeyResponse:
    properties:
      apiKey:
        type: string
    type: object
  server.ErrorReason:
    properties:
      reason:
        example: reason
        type: string
    type: object
  server.UserCredentials:
    properties:
      password:
        example: Password123
        minLength: 3
        type: string
      username:
        example: JohnDoe
        maxLength: 20
        minLength: 4
        type: string
    type: object
info:
  contact: {}
  description: chess api for playing chess online.
  license:
    name: MIT
  title: Chess API
paths:
  /auth/login:
    post:
      consumes:
      - application/json
      description: |-
        Log into an account using provided username and password. And get an API key.
        Username can be between 3-20 characters.
        Password must be at least 3 characters.
      parameters:
      - description: Login Account
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/server.UserCredentials'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/server.ApiKeyResponse'
        "401":
          description: Invalid username/password
          schema:
            $ref: '#/definitions/server.ErrorReason'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/server.ErrorReason'
      summary: Log into an account and get an API key.
      tags:
      - auth
  /games:
    post:
      consumes:
      - application/json
      description: Authorized users can make a match and receive a sharable link for
        anyone to play with them.
      parameters:
      - description: 'Must contain JWT from auth/login in the format Bearer: <JWT>'
        in: header
        name: Authorization
        required: true
        type: string
      responses: {}
      summary: Create a match, and get a sharable link.
      tags:
      - games
  /users:
    post:
      consumes:
      - application/json
      description: |-
        Username can be between 3-20 characters.
        Password must be at least 3 characters.
      parameters:
      - description: Register Account
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/server.UserCredentials'
      produces:
      - application/json
      responses:
        "201":
          description: Api Key
          schema:
            $ref: '#/definitions/server.ApiKeyResponse'
        "400":
          description: Invalid credentials
          schema:
            $ref: '#/definitions/server.ErrorReason'
        "409":
          description: Username already exists
          schema:
            $ref: '#/definitions/server.ErrorReason'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/server.ErrorReason'
      summary: Create an account using provided username and password.
      tags:
      - users
swagger: "2.0"
